### ISSUE TITLE
Issues with + and /

### ISSUE THREAD

**Issue by Speedstack79** [PenguinGovernor/Base-64v2.01#1]
Entering 'z+' returns 3966
changing this to 'z/' returns 3903

Seems to be edge case error (< instead of <= or vice versa)  in one of the loops because changing any input from X+ to X/ seems to change the number by a constant value of 63 (oop looks like the last number of base64)  instead of 1.

**Comment by PenguinGovernor** [comment]
Looks like I had 

```javascript
var base64Array =[...,"+","/s]; 
```

So every time base64Array.indexOf("/") was called it would return a value of -1 as "/" did not exist in the array 

However, I fixed this in the last commit and now base64Array.indexOf("/") properly returns its correct value. 

Just goes to show that typos can be catastrophic whilst programming :wink:
